apiVersion: v1
kind: ConfigMap
metadata:
  name: shortly-nginx-configmap
  namespace: shortly-prod
data:
  shortly.conf: |-
    upstream application {
        server 127.0.0.1:9000;
    }

    server {
        listen 80;
        client_max_body_size 64m;

        root /var/www/public;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
            fastcgi_pass application;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            fastcgi_index index.php;

            include fastcgi_params;
            fastcgi_read_timeout 300;

            fastcgi_param SCRIPT_FILENAME /var/shortly/public/$fastcgi_script_name;

            internal;
        }

        location ~ \.php$ {
            return 404;
        }
    }

  nginx.conf: |-
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*.conf;
    }


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shortly-configmap
  namespace: shortly-prod
data:
  APP_NAME: "Laravel"
  APP_ENV: "prod"
  APP_KEY: "base64:Hj3Rl7dKvq2Cq3Jbeg6w9wRck7yiozR9ofNZFM6ai1M="
  APP_DEBUG: "false"
  APP_URL: "http://shortly.local"
  LOG_CHANNEL: "stack"
  DB_CONNECTION: "mysql"
  DB_HOST: "db"
  DB_PORT: "3306"
  DB_DATABASE: "shortly"
  DB_USERNAME: "main"
  DB_PASSWORD: "qwerty"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "redis"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
  REDIS_HOST: "redis"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

