apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortly-nginx-phpfpm
  namespace: shortly-prod
spec:
  replicas: 1
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app: shortly-app
  template:
    metadata:
      labels:
        app: shortly-app
    spec:
      initContainers:
        - name: assets
          image: bahdall/shortly-php-fpm-prod:{{image_tag}}
          command: ["/bin/sh", "-c", "cp -r /var/www/public/* /mnt/;"]
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /mnt
              name: shared-files
      containers:
        - image: nginx:alpine
          name: shortly-nginx
          envFrom:
            - configMapRef:
                name: shortly-nginx-configmap
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume-shortly
              mountPath: /etc/nginx/sites-enabled/shortly.conf
              subPath: shortly.conf
            - name: nginx-config-volume-nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: shared-files
              mountPath: /var/shortly/public
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "500m"

        - image: bahdall/shortly-php-fpm-prod:{{image_tag}}
          name: shortly-phpfpm
          envFrom:
            - configMapRef:
                name: shortly-configmap
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          volumeMounts:
            - name: shared-files
              mountPath: /mnt
      volumes:
        - name: nginx-config-volume-shortly
          configMap:
            name: shortly-nginx-configmap
        - name: nginx-config-volume-nginx
          configMap:
            name: shortly-nginx-configmap
        - name: shared-files
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shortly-app
  name: shortly-service
  namespace: shortly-prod
spec:
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30333
  selector:
    app: shortly-app
  type: NodePort
